### PR TITLE
added query data

### PR DESCRIPTION
**Pull request by dmgburg**
Added a way to filter wmi object fields and filtering conditions

### CODE REVIEW

**Comment by profesorfalken** [comment]
Hello! No luck. I had done some changes some minutes before your pull request and now the branch is in conflict. Could you merge, fix the conflicts and redone the pull request?. 
The functionality you have added seems interesting.

Thank you very much

**Comment by dmgburg** [comment]
Too bad. Sure, I'll merge in a minute. Just finishig changes in jProcesses.
BTW, I can't get what do you get from fillExtraProcessData in org.jutils.jprocesses.info.WindowsProcessesService#getProcessesData? 
If you need to optimize things this is your first candidate to remove, it takes about 70% of time

**Comment by profesorfalken** [comment]
Cool, thank you!, I am going to accept it this evening (France time) and versioning it.

**Comment by profesorfalken** [comment]
It is OK for WMI4Java. The version 1.3 is ready containing the new methods and it will be also available on Maven central in less than a day.

I will take a look tomorrow for jProcesses.

Thank you again for your contribution

**Pull request merged**
